### ISSUE TITLE
My friends can't use the drugs

### ISSUE THREAD

**Issue by IAmPandaLord** [Chafficui/MyTrip#3]
I am somewhat new to plugins but I can't figure out how to give permission to use the drugs. It just says they can't use them whenever they right click with it in their hand.

**Comment by Chafficui** [comment]
You have to download a permissions plugin and assign the permissions listed in my Wiki to them :)

**Comment by Chafficui** [comment]
Here is a permissions plugin tutorial: https://youtu.be/CwlXkTbuAng
And here is the link to my wiki: https://github.com/Chafficui/MyTrip/wiki/Commands-&-Permissions

**Comment by Chafficui** [comment]
Permission for use of all drugs in v0.3.5 is mytrip.use.*. If you want to craft them you can give them the permission mytrip.craft.*. For drugging station it's mytrip.use.druggingstation and mytrip.craft.druggingstation.

**Comment by IAmPandaLord** [comment]
Do you know exactly which plugin? I’m not great with all of this stuff.

**Comment by IAmPandaLord** [comment]
Nvm😂 sorry. I see the link now

**Comment by Chafficui** [comment]
If you are having any other problems, just tell me :)

**Comment by IAmPandaLord** [comment]
Thank you. I will.
