### ISSUE TITLE
0.4.2 Bugs

### ISSUE THREAD

**Issue by Keith-Driscoll** [Chafficui/MyTrip#4]
Every minute or so the console keeps issuing the same command. It's not a major issue but thought it should be addressed - ![image](https://user-images.githubusercontent.com/13069412/80166560-2ea0b100-85d6-11ea-985b-dcc5f389f2ca.png)

Another issue I have is, I've installed the 0.4.2 jar file onto my server but the config.yml file identifies the version as 0.4.1. If I try to manually rename the version in the config file, the plugin will no longer work.

**Comment by Chafficui** [comment]
Thanks for messaging me these issues! 
I've fixed the second thing in v0.4.3. I don't rly know the reason for the first bug. Maybe it's fixed with a restart.

**Comment by Keith-Driscoll** [comment]
I've updated to 0.4.3 and the other issues have been fixed but the console issue is still there:

![image](https://user-images.githubusercontent.com/13069412/80204541-fb374400-8620-11ea-8be1-f264c7634b45.png)

**Comment by Chafficui** [comment]
Ok let me see if I can spot the issue

**Comment by Chafficui** [comment]
https://drive.google.com/open?id=1VTyzp24tD-G6JwjvFgESSqKRBPDjvW0F
Could you try using this file? Tell me if it fixes the error :)

**Comment by Keith-Driscoll** [comment]
That seems to have did the trick! Thanks!

_By the way, great plugin so far. I'm really enjoying it!_

**One idea** I would like to suggest could be alter the **anti-toxin** to only remove the negative effects of drugs(things that deal damage). At the moment it just removes all potion effects and it's tricky to craft. I just use a bucket of milk instead, with the same result.

**Comment by Chafficui** [comment]
I didn't think of this.... you're totally right. I'll do this in next version I think.
I close this ticket now. if you're having any different issues, just create a new one.
