### ISSUE TITLE
The plugin was working up until today on our server

### ISSUE THREAD

**Issue by nick6288** [Chafficui/MyTrip#6]
On our server the mod was working perfectly but when we logged on today nothing was working and we tried reinstalling and restarting the server and reinstalling spigot but nothing worked. It gave us an error when we tried to run the command and it said internal error when trying to run this command.

**Comment by Chafficui** [comment]
Can you tell me some more information please? What Server version are you using? What plugin version. Can you upload the errors please?
Did you delete the MyTrip folder after updating to v0.6?

**Comment by nick6288** [comment]
We are using the latest 0.6.2 for the my trip plugin and the server version is spigot 1.16.3 and we tried also using paper 1.16.3 which was the one that gave us the error code that said “an internal error occurred while attempting to perform this command” when the /mt command was run. On the spigot version nothing happens when the command is run and the modded items that we already have are unusable and don’t do anything. We just tried to delete the folder and reinstall and it works now. We will see if it continues to work and will come back if something happens. Thank you!

**Comment by Chafficui** [comment]
Ok nice. Can you tell me what errors occured while using the paper version? I tested it in paper and everything was fine :/

**Comment by FlqmingPig** [comment]
I found this error showing on my console, that's probably why the commands don't work.
https://paste.ubuntu.com/p/nxXpNxrgPd/

**Comment by Chafficui** [comment]
@FlqmingPig thanks. Did you try to delete the MyTrip Folder and reloaded the server?

**Comment by FlqmingPig** [comment]
I haven't tried that yet.

**Comment by Chafficui** [comment]
It should fix this. There is an issue with a item

**Comment by FlqmingPig** [comment]
Alright, I'll try it later today

**Comment by FlqmingPig** [comment]
Alright it works now
